INSERT INTO user (id, username, password_hash)
VALUES (1, 'Bret', '123123123123'),
       (2, 'Antonette', 'ertertertert'),
       (3, 'Samantha', 'asdipufh987p3145'),
       (4, 'Karianne', 'klsduf870wer'),
       (5, 'Kamren', '1982eyhniousdhf'),
       (6, 'Leopoldo_Corkery', '9w8eynrc92'),
       (7, 'Elwyn.Skiles', '9812-nc43yr13984r'),
       (8, 'Maxime_Nienow', '1349c8n0yr'),
       (9, 'Delphine', '134crn0987y31'),
       (10, 'Moriah.Stanton', '13908n4cyrj1r');

# TODO: add date created
INSERT INTO article (author_id, id, title, content)
VALUES (1, 1, 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
        'quia et suscipit↵suscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto'),
       (1, 2, 'qui est esse',
        'est rerum tempore vitae↵sequi sint nihil reprehend…aperiam non debitis possimus qui neque nisi nulla'),
       (1, 3, 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
        'et iusto sed quo iure↵voluptatem occaecati omnis e…↵molestiae porro eius odio et labore et velit aut'),
       (1, 4, 'eum et est occaecati',
        'ullam et saepe reiciendis voluptatem adipisci↵sit … ipsam iure↵quis sunt voluptatem rerum illo velit'),
       (1, 5, 'nesciunt quas odio',
        'repudiandae veniam quaerat sunt sed↵alias aut fugi…sse voluptatibus quis↵est aut tenetur dolor neque'),
       (1, 6, 'dolorem eum magni eos aperiam quia',
        'ut aspernatur corporis harum nihil quis provident …s↵voluptate dolores velit et doloremque molestiae'),
       (1, 7, 'magnam facilis autem',
        'dolore placeat quibusdam ea quo vitae↵magni quis e…t excepturi ut quia↵sunt ut sequi eos ea sed quas'),
       (1, 8, 'dolorem dolore est ipsam',
        'dignissimos aperiam dolorem qui eum↵facilis quibus…↵ipsam ut commodi dolor voluptatum modi aut vitae'),
       (1, 9, 'nesciunt iure omnis dolorem tempora et accusantium',
        'consectetur animi nesciunt iure dolore↵enim quia a…st aut quod aut provident voluptas autem voluptas'),
       (1, 10, 'optio molestias id quia eum',
        'quo et expedita modi cum officia vel magni↵dolorib…it↵quos veniam quod sed accusamus veritatis error'),
       (2, 11, 'et ea vero quia laudantium autem',
        'delectus reiciendis molestiae occaecati non minima…luptates ut commodi qui incidunt↵ut animi commodi'),
       (2, 12, 'in quibusdam tempore odit est dolorem',
        'itaque id aut magnam↵praesentium quia et ea odit e…uia id voluptatem↵incidunt ea est distinctio odio'),
       (2, 13, 'dolorum ut in voluptas mollitia et saepe quo animi',
        'aut dicta possimus sint mollitia voluptas commodi …ssumenda consectetur porro architecto ipsum ipsam'),
       (2, 14, 'voluptatem eligendi optio',
        'fuga et accusamus dolorum perferendis illo volupta…molestiae beatae↵sed aut voluptas totam sit illum'),
       (2, 15, 'eveniet quod temporibus',
        'reprehenderit quos placeat↵velit minima officia do…usandae quis delectus↵officiis harum fugiat vitae'),
       (2, 16, 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio',
        'suscipit nam nisi quo aperiam aut↵asperiores eos f… magni mollitia accusamus ea nisi voluptate dicta'),
       (2, 17, 'fugit voluptas sed molestias voluptatem provident',
        'eos voluptas et aut odit natus earum↵aspernatur fu…ui eos↵qui nihil ratione nemo velit ut aut id quo'),
       (2, 18, 'voluptate et itaque vero tempora molestiae',
        'eveniet quo quis↵laborum totam consequatur non dol… repudiandae↵est voluptatem vel debitis et magnam'),
       (2, 19, 'adipisci placeat illum aut reiciendis qui',
        'illum quis cupiditate provident sit magnam↵ea sed …tque↵adipisci quo iste expedita sit quos voluptas'),
       (2, 20, 'doloribus ad provident suscipit at',
        'qui consequuntur ducimus possimus quisquam amet si…erum consequatur expedita quidem cumque explicabo'),
       (3, 21, 'asperiores ea ipsam voluptatibus modi minima quia sint',
        'repellat aliquid praesentium dolorem quo↵sed totam…ecusandae veniam↵tempora et tenetur expedita sunt'),
       (3, 22, 'dolor sint quo a velit explicabo quia nam',
        'eos qui et ipsum ipsam suscipit aut↵sed omnis non …molestiae aut atque rem suscipit↵nam impedit esse'),
       (3, 23, 'maxime id vitae nihil numquam',
        'veritatis unde neque eligendi↵quae quod architecto…t vel beatae sequi ullam sed tenetur perspiciatis'),
       (3, 24, 'autem hic labore sunt dolores incidunt',
        'enim et ex nulla↵omnis voluptas quia qui↵voluptate…sandae id dignissimos aut sed asperiores deserunt'),
       (3, 25, 'rem alias distinctio quo quis',
        'ullam consequatur ut↵omnis quis sit vel consequunt…nostrum↵molestiae illo tempore quia et distinctio'),
       (3, 26, 'est et quae odit qui non',
        'similique esse doloribus nihil accusamus↵omnis dol…is cum ut laudantium↵omnis aut molestiae vel vero'),
       (3, 27, 'quasi id et eos tenetur aut quo autem',
        'eum sed dolores ipsam sint possimus debitis occaec…atibus rerum sed inventore temporibus consequatur'),
       (3, 28, 'delectus ullam et corporis nulla voluptas sequi',
        'non et quaerat ex quae ad maiores↵maiores recusand…↵ut voluptatibus voluptatem↵similique nostrum eum'),
       (3, 29, 'iusto eius quod necessitatibus culpa ea',
        'odit magnam ut saepe sed non qui↵tempora atque nih… repudiandae odit magni similique sed cum maiores'),
       (3, 30, 'a quo magni similique perferendis',
        'alias dolor cumque↵impedit blanditiis non eveniet …pora quia autem rem↵a provident perspiciatis quia'),
       (4, 31, 'ullam ut quidem id aut vel consequuntur',
        'debitis eius sed quibusdam non quis consectetur vi…sci atque↵quaerat voluptatem adipisci repudiandae'),
       (4, 32, 'doloremque illum aliquid sunt',
        'deserunt eos nobis asperiores et hic↵est debitis r…ptates et aut adipisci ea maiores voluptas maxime'),
       (4, 33, 'qui explicabo molestiae dolorem',
        'rerum ut et numquam laborum odit est sit↵id qui si…t quaerat qui in↵rerum officiis sequi cumque quod'),
       (4, 34, 'magnam ut rerum iure',
        'ea velit perferendis earum ut voluptatem voluptate…enda accusamus dignissimos officia nesciunt nobis'),
       (4, 35, 'id nihil consequatur molestias animi provident',
        'nisi error delectus possimus ut eligendi vitae↵pla…s quo illum voluptas eligendi↵et nobis quia fugit'),
       (4, 36, 'fuga nam accusamus voluptas reiciendis itaque',
        'ad mollitia et omnis minus architecto odit↵volupta…ti↵qui aspernatur quia eaque ut aperiam inventore'),
       (4, 37, 'provident vel ut sit ratione est',
        'debitis et eaque non officia sed nesciunt pariatur…s omnis consequatur aut enim officiis in quam qui'),
       (4, 38, 'explicabo et eos deleniti nostrum ab id repellendus',
        'animi esse sit aut sit nesciunt assumenda eum volu…t aut id quia↵ratione optio eos iusto veniam iure'),
       (4, 39, 'eos dolorem iste accusantium est eaque quam',
        'corporis rerum ducimus vel eum accusantium↵maxime … sapiente vel dolore minus voluptatem incidunt ex'),
       (4, 40, 'enim quo cumque',
        'ut voluptatum aliquid illo tenetur nemo sequi quo …e omnis voluptatem iure quasi maxime voluptas nam'),
       (5, 41, 'non est facere',
        'molestias id nostrum↵excepturi molestiae dolore om…s ex ut↵nam quidem est ducimus sunt debitis saepe'),
       (5, 42, 'commodi ullam sint et excepturi error explicabo praesentium voluptas',
        'odio fugit voluptatum ducimus earum autem est inci…epellendus voluptates quia↵ratione harum vitae ut'),
       (5, 43, 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis',
        'similique fugit est↵illum et dolorum harum et volu…ercitationem magnam ex et a et distinctio debitis'),
       (5, 44, 'optio dolor molestias sit',
        'temporibus est consectetur dolore↵et libero debiti…aut↵ea et iure quam sed maxime ut distinctio quae'),
       (5, 45, 'ut numquam possimus omnis eius suscipit laudantium iure',
        'est natus reiciendis nihil possimus aut provident↵…ariatur est↵nobis rerum repellendus dolorem autem'),
       (5, 46, 'aut quo modi neque nostrum ducimus',
        'voluptatem quisquam iste↵voluptatibus natus offici…orem↵quis quas ipsam↵vel et voluptatum in aliquid'),
       (5, 47, 'quibusdam cumque rem aut deserunt',
        'voluptatem assumenda ut qui ut cupiditate aut impe…erum ea iure soluta nostrum↵eligendi et voluptate'),
       (5, 48, 'ut voluptatem illum ea doloribus itaque eos',
        'voluptates quo voluptatem facilis iure occaecati↵v…↵laudantium repellat ad ut et autem reprehenderit'),
       (5, 49, 'laborum non sunt aut ut assumenda perspiciatis voluptas',
        'inventore ab sint↵natus fugit id nulla sequi archi…busdam officiis aspernatur cumque aut commodi aut'),
       (5, 50, 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem',
        'error suscipit maxime adipisci consequuntur recusa…↵adipisci impedit sequi nesciunt quis consectetur'),
       (6, 51, 'soluta aliquam aperiam consequatur illo quis voluptas',
        'sunt dolores aut doloribus↵dolore doloribus volupt…que et quo↵cum asperiores sit consectetur dolorem'),
       (6, 52, 'qui enim et consequuntur quia animi quis voluptate quibusdam',
        'iusto est quibusdam fuga quas quaerat molestias↵a … architecto↵soluta esse reprehenderit qui laborum'),
       (6, 53, 'ut quo aut ducimus alias',
        'minima harum praesentium eum rerum illo dolore↵qua…lor quidem veritatis sunt non explicabo similique'),
       (6, 54, 'sit asperiores ipsam eveniet odio non quia',
        'totam corporis dignissimos↵vitae dolorem ut occaec…et exercitationem vero incidunt corrupti mollitia'),
       (6, 55, 'sit vel voluptatem et non libero',
        'debitis excepturi ea perferendis harum libero opti…↵et ut incidunt omnis molestiae↵nihil ut eum odit'),
       (6, 56, 'qui et at rerum necessitatibus',
        'aut est omnis dolores↵neque rerum quod ea rerum ve…pti↵corporis harum reprehenderit dolores eligendi'),
       (6, 57, 'sed ab est est',
        'at pariatur consequuntur earum quidem↵quo est laud…am et est↵et cum voluptas voluptatum repellat est'),
       (6, 58, 'voluptatum itaque dolores nisi et quasi',
        'veniam voluptatum quae adipisci id↵et id quia eos …o nisi sunt eos impedit error↵ad similique veniam'),
       (6, 59, 'qui commodi dolor at maiores et quis id accusantium',
        'perspiciatis et quam ea autem temporibus non volup… quas et magni↵et hic ut ut commodi expedita sunt'),
       (6, 60, 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere',
        'asperiores sunt ab assumenda cumque modi velit↵qui…rferendis voluptas↵illo ratione amet aut et omnis'),
       (7, 61, 'voluptatem doloribus consectetur est ut ducimus',
        'ab nemo optio odio↵delectus tenetur corporis simil…sciunt doloribus dicta dolores↵magnam minus velit'),
       (7, 62, 'beatae enim quia vel',
        'enim aspernatur illo distinctio quae praesentium↵b… autem omnis↵quo molestiae omnis ea eveniet optio'),
       (7, 63, 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit',
        'enim adipisci aspernatur nemo↵numquam omnis facere…tium ut quam in voluptatibus voluptas ipsam dicta'),
       (7, 64, 'et fugit quas eum in in aperiam quod',
        'id velit blanditiis↵eum ea voluptatem↵molestiae si…atis↵incidunt a error provident eaque aut aut qui'),
       (7, 65, 'consequatur id enim sunt et et',
        'voluptatibus ex esse↵sint explicabo est aliquid cu…es et perferendis↵natus id esse incidunt pariatur'),
       (7, 66, 'repudiandae ea animi iusto',
        'officia veritatis tenetur vero qui itaque↵sint non…e nostrum↵veritatis quibusdam et nemo iusto saepe'),
       (7, 67, 'aliquid eos sed fuga est maxime repellendus',
        'reprehenderit id nostrum↵voluptas doloremque paria… sapiente et consequatur necessitatibus molestiae'),
       (7, 68, 'odio quis facere architecto reiciendis optio',
        'magnam molestiae perferendis quisquam↵qui cum reic…ventore↵ea quia deleniti quidem saepe porro velit'),
       (7, 69, 'fugiat quod pariatur odit minima',
        'officiis error culpa consequatur modi asperiores e…s↵sequi commodi repudiandae asperiores et saepe a'),
       (7, 70, 'voluptatem laborum magni',
        'sunt repellendus quae↵est asperiores aut deleniti …uia aut↵quia dolorem unde↵eum tempora esse dolore'),
       (8, 71, 'et iusto veniam et illum aut fuga',
        'occaecati a doloribus↵iste saepe consectetur place…a voluptas↵rerum ut id enim velit est perferendis'),
       (8, 72, 'sint hic doloribus consequatur eos non id',
        'quam occaecati qui deleniti consectetur↵consequatu…cusamus↵sunt consectetur expedita inventore velit'),
       (8, 73, 'consequuntur deleniti eos quia temporibus ab aliquid at',
        'voluptatem cumque tenetur consequatur expedita ips…t et↵et in consequuntur voluptatem voluptates aut'),
       (8, 74, 'enim unde ratione doloribus quas enim ut sit sapiente',
        'odit qui et et necessitatibus sint veniam↵mollitia…uo et tenetur ratione occaecati molestiae tempora'),
       (8, 75, 'dignissimos eum dolor ut enim et delectus in',
        'commodi non non omnis et voluptas sit↵autem aut no…et nemo voluptate expedita adipisci error dolorem'),
       (8, 76, 'doloremque officiis ad et non perferendis',
        'ut animi facere↵totam iusto tempore↵molestiae eum … et dolorem aperiam↵quaerat recusandae totam odio'),
       (8, 77, 'necessitatibus quasi exercitationem odio',
        'modi ut in nulla repudiandae dolorum nostrum eos↵a…eriores nobis amet corrupti repudiandae provident'),
       (8, 78, 'quam voluptatibus rerum veritatis',
        'nobis facilis odit tempore cupiditate quia↵assumen… qui ea↵illum et qui totam↵aut veniam repellendus'),
       (8, 79, 'pariatur consequatur quia magnam autem omnis non amet',
        'libero accusantium et et facere incidunt sit dolor… ducimus est↵officiis esse molestiae iste et quos'),
       (8, 80, 'labore in ex et explicabo corporis aut quas',
        'ex quod dolorem ea eum iure qui provident amet↵qui…nt vero fugit rerum sint sunt excepturi provident'),
       (9, 81, 'tempora rem veritatis voluptas quo dolores vero',
        'facere qui nesciunt est voluptatum voluptatem nisi…tur↵ex officiis minima doloremque voluptas ut aut'),
       (9, 82, 'laudantium voluptate suscipit sunt enim enim',
        'ut libero sit aut totam inventore sunt↵porro sint …ssumenda soluta laboriosam amet iste delectus hic'),
       (9, 83, 'odit et voluptates doloribus alias odio et',
        'est molestiae facilis quis tempora numquam nihil q…i dolore numquam↵reprehenderit eius rem quibusdam'),
       (9, 84, 'optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut',
        'sint molestiae magni a et quos↵eaque et quasi↵ut r…andae dignissimos dolor incidunt consequatur odio'),
       (9, 85, 'dolore veritatis porro provident adipisci blanditiis et sunt',
        'similique sed nisi voluptas iusto omnis↵mollitia e…ent pariatur praesentium atque animi amet ratione'),
       (9, 86, 'placeat quia et porro iste',
        'quasi excepturi consequatur iste autem temporibus …xplicabo autem↵asperiores pariatur deserunt optio'),
       (9, 87, 'nostrum quis quasi placeat',
        'eos et molestiae↵nesciunt ut a↵dolores perspiciati…lendus repellat aliquid↵magnam sint rem ipsum est'),
       (9, 88, 'sapiente omnis fugit eos',
        'consequatur omnis est praesentium↵ducimus non iste…hic deserunt↵voluptatibus veniam cum et rerum sed'),
       (9, 89, 'sint soluta et vel magnam aut ut sed qui',
        'repellat aut aperiam totam temporibus autem et↵arc…ia soluta dignissimos nihil iure↵tempore quas est'),
       (9, 90, 'ad iusto omnis odit dolor voluptatibus',
        'minus omnis soluta quia↵qui sed adipisci voluptate…soluta similique molestias praesentium blanditiis'),
       (10, 91, 'aut amet sed',
        'libero voluptate eveniet aperiam sed↵sunt placeat …nsequatur consequatur dolores quia eos et placeat'),
       (10, 92, 'ratione ex tenetur perferendis',
        'aut et excepturi dicta laudantium sint rerum nihil…icia et similique libero et↵commodi voluptate qui'),
       (10, 93, 'beatae soluta recusandae',
        'dolorem quibusdam ducimus consequuntur dicta aut q…am↵sit error sed sunt eveniet provident qui nulla'),
       (10, 94, 'qui qui voluptates illo iste minima',
        'aspernatur expedita soluta quo ab ut similique↵exp…mnis facilis nam ipsum natus sint similique omnis'),
       (10, 95, 'id minus libero illum nam ad officiis',
        'earum voluptatem facere provident blanditiis velit…s↵corporis cupiditate eaque assumenda ad nesciunt'),
       (10, 96, 'quaerat velit veniam amet cupiditate aut numquam ut sequi',
        'in non odio excepturi sint eum↵labore voluptates v…aque rerum↵veniam non exercitationem delectus aut'),
       (10, 97, 'quas fugiat ut perspiciatis vero provident',
        'eum non blanditiis soluta porro quibusdam voluptas…st et voluptatem dignissimos dolor itaque sit nam'),
       (10, 98, 'laboriosam dolor voluptates',
        'doloremque ex facilis sit sint culpa↵soluta assume…ius↵sequi ducimus vel quasi↵veritatis est dolores'),
       (10, 99, 'temporibus sit alias delectus eligendi possimus magni',
        'quo deleniti praesentium dicta non quod↵aut est mo…lestias et officia quis nihil↵itaque dolorem quia'),
       (10, 100, 'at nam consequatur ea labore ea harum',
        'cupiditate quo est a modi nesciunt soluta↵ipsa vol…nam et distinctio eum↵accusamus ratione error aut');
